.PHONY: clean All

All:
	@echo "----------Building project:[ PROJECT1 - Debug ]----------"
	@cd "PROJECT1" && "$(MAKE)" -f  "PROJECT1.mk"
clean:
	@echo "----------Cleaning project:[ PROJECT1 - Debug ]----------"
	@cd "PROJECT1" && "$(MAKE)" -f  "PROJECT1.mk" clean
